In [1]:
import pandas as pd
import random
import numpy as np
import datetime

In [2]:
def get_win_probabilities(team1, team2, rankings):
    team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
    team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
    total = team1_total + team2_total
    team1_prob = 1 - (team1_total * 1.0 / total)
    team2_prob = 1 - (team2_total * 1.0 / total)
    return team1_prob, team2_prob

In [3]:
dartboard_numbers = [20, 1, 18, 4, 13, 6, 10, 15, 2, 17, 3, 19, 7, 16, 8, 11, 14, 9, 12, 5]

# Indices for special positions
vertical_indices = [0, 10]      # 20 (top), 3 (bottom)
horizontal_indices = [5, 15]    # 6 (right), 11 (left)

# Build weights: 6 down to 1, then up to 6
descending = [7, 6, 5, 5, 4, 3]
ascending = [4, 5, 5, 6]
weights_first_half = descending + ascending  # 6,5,4,3,2,1,2,3,4,5 (10 numbers)
#weights_second_half = weights_first_half[::-1]  # Mirror for the second half

dartboard_weights_list = weights_first_half + weights_first_half  # 20 numbers

# Map weights to numbers
dartboard_weights = {num: weight for num, weight in zip(dartboard_numbers, dartboard_weights_list)}

# For reference, print the mapping
for num in dartboard_numbers:
    print(f"{num}: {dartboard_weights[num]}")

20: 7
1: 6
18: 5
4: 5
13: 4
6: 3
10: 4
15: 5
2: 5
17: 6
3: 7
19: 6
7: 5
16: 5
8: 4
11: 3
14: 4
9: 5
12: 5
5: 6

In [4]:
def get_dartboard_numbers(team1, team2, rankings, dartboard_numbers, dartboard_weights,
                          n_trials=2000, temperature=0.35, seed=None, return_debug=False):
    if seed is not None:
        random.seed(seed)

    # Probabilities from your function
    team1_prob, team2_prob = get_win_probabilities(team1, team2, rankings)

    total_weight = sum(dartboard_weights[n] for n in dartboard_numbers)
    team1_target = total_weight * team1_prob

    best = None  # (score, assignments_dict, team1_weight, team2_weight)

    for _ in range(n_trials):
        nums = dartboard_numbers[:]
        random.shuffle(nums)

        assignments = {}
        w1 = 0
        w2 = 0

        for n in nums:
            w = dartboard_weights[n]

            # Remaining "need" to hit the target (positive means still needs weight)
            need1 = team1_target - w1
            need2 = (total_weight - team1_target) - w2

            # Soft preference for the team that needs more weight
            # Convert needs into a probability using a squashed function
            # temperature controls randomness: smaller => more deterministic
            x = (need1 - need2) / max(1.0, temperature * total_weight)
            p_team1 = 1.0 / (1.0 + (2.718281828 ** (-x)))

            if random.random() < p_team1:
                assignments[n] = team1
                w1 += w
            else:
                assignments[n] = team2
                w2 += w

        # Score: closeness to team1_target (team2 is implied since totals sum)
        score = abs(w1 - team1_target)

        # Keep best (tie-break with a little randomness so repeated runs vary)
        if best is None or score < best[0] or (score == best[0] and random.random() < 0.5):
            best = (score, assignments, w1, w2)

    _, assignments, w1, w2 = best

    team_list = pd.Series(assignments).sort_index()

    if return_debug:
        return team_list, {
            "team1_prob": team1_prob,
            "team2_prob": team2_prob,
            "total_weight": total_weight,
            "team1_target": team1_target,
            "team1_weight": w1,
            "team2_weight": w2,
            "abs_error": abs(w1 - team1_target),
        }

    return team_list

In [5]:
# NOTE FOR 2026 - Weight the vertical numbers more than the horizontal numbers
def get_dartboard_numbers_old(team1, team2):
    team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
    team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
    total = team1_total + team2_total
    
    team1_prob = 1 - (team1_total * 1.0 / total)
    team2_prob = 1 - (team2_total * 1.0 / total)
    
    team1_size = team1_prob * 20
    team2_size = team2_prob * 20
    team1_size = round(team1_size,0)
    team2_size = round(team2_size,0)
    
    team_list = [team1] * int(team1_size) + [team2] * int(team2_size)
    
    num_shuffles = random.randint(1,50)
    for i in range(1,num_shuffles):
        random.shuffle(team_list)
        
    team_list = pd.Series(team_list)
    team_list.index += 1
    
    print (team_list)

In [6]:
def select_winner(team1, team2, rankings):
    # Probabilities from your function
    team1_prob, team2_prob = get_win_probabilities(team1, team2, rankings)
    
    team1_size = team1_prob * 100
    team2_size = team2_prob * 100
    team1_size = round(team1_size,0)
    team2_size = round(team2_size,0)
    
    team_list = [team1] * int(team1_size) + [team2] * int(team2_size)
    
    num_shuffles = random.randint(1,50)
    for i in range(1,num_shuffles):
        random.shuffle(team_list)
        
    team_list = pd.Series(team_list)
    team_list.index += 1
    
    return team_list[1]

In [7]:
rankings = pd.read_csv('CBB Rankings - 2026.csv')
rankings.set_index('Team', inplace=True)

In [68]:
# rankings.drop('Recent Rank', axis=1, inplace=True)

In [8]:
rankings.head(10)

               Bracket Order  Seed  Ken Pom  Off Eff  Def Eff  NET Ranking
Team
Duke                       1     1        1        4        2            1
Siena                      2    16      192      210      175          183
Ohio St.                   3     8       26       17       54           29
TCU                        4     9       43       81       22           39
St. John's                 5     5       17       44       12           16
Northern Iowa              6    12       72      153       24           72
Kansas                     7     4       21       57       10           21
Cal Baptist                8    13      106      191       50           98
Louisville                 9     6       19       19       25           17
South Florida             10    11       47       61       40           45

In [9]:
rankings.loc["Duke"]

Bracket Order    1
Seed             1
Ken Pom          1
Off Eff          4
Def Eff          2
NET Ranking      1
Name: Duke, dtype: int64

In [12]:
rankings.index

Index(['Duke', 'Siena', 'Ohio St.', 'TCU', 'St. John's', 'Northern Iowa',
       'Kansas', 'Cal Baptist', 'Louisville', 'South Florida', 'Michigan St.',
       'North Dakota St.', 'UCLA', 'UCF', 'Uconn', 'Furman', 'Florida',
       'Prairie View A&M', 'Clemson', 'Iowa', 'Vanderbilt', 'McNeese',
       'Nebraska', 'Troy', 'North Carolina', 'VCU', 'Illinois', 'Penn',
       'Saint Mary's', 'Texas A&M', 'Houston', 'Idaho', 'Arizona', 'LIU',
       'Villanova', 'Utah St.', 'Wisconsin', 'High Point', 'Arkansas',
       'Hawaii', 'BYU', 'Texas', 'Gonzaga', 'Kennesaw St.', 'Miami (FL)',
       'Missouri', 'Purdue', 'Queens', 'Michigan', 'Howard', 'Georgia',
       'Saint Louis', 'Texas Tech', 'Akron', 'Alabama', 'Hofstra', 'Tennessee',
       'SMU', 'Virginia', 'Wright St.', 'Kentucky', 'Santa Clara', 'Iowa St.',
       'Tennessee St.'],
      dtype='object', name='Team')

In [13]:
bracket = pd.DataFrame(rankings.index)
bracket.index += 1
bracket = bracket[:64]
bracket.head()

         Team
1        Duke
2       Siena
3    Ohio St.
4         TCU
5  St. John's

In [14]:
for i in range(1,len(bracket),2):
    team1 = bracket['Team'][i]
    team2 = bracket['Team'][i+1]
    team1_prob, team2_prob = get_win_probabilities(team1, team2, rankings)
    print ()
    print (team1, ' (',f"{team1_prob:.1%}", ') vs. ', team2, ' (',f"{team2_prob:.1%}",')')
    print (get_dartboard_numbers(team1, team2, rankings, dartboard_numbers, dartboard_weights))
    print ()

C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]

Duke  ( 98.6% ) vs.  Siena  ( 1.4% )
1     Duke
2     Duke
3     Duke
4     Duke
5     Duke
6     Duke
7     Duke
8     Duke
9     Duke
10    Duke
11    Duke
12    Duke
13    Duke
14    Duke
15    Duke
16    Duke
17    Duke
18    Duke
19    Duke
20    Duke
dtype: object


Ohio St.  ( 58.3% ) vs.  TCU  ( 41.7% )
1     Ohio St.
2          TCU
3          TCU
4     Ohio St.
5          TCU
6          TCU
7     Ohio St.
8     Ohio St.
9     Ohio St.
10         TCU
11         TCU
12    Ohio St.
13         TCU
14    Ohio St.
15         TCU
16    Ohio St.
17    Ohio St.
18         TCU
19    Ohio St.
20    Ohio St.
dtype: object


St. John's  ( 77.2% ) vs.  Northern Iowa  ( 22.8% )
1     Northern Iowa
2     Northern Iowa
3        St. John's
4        St. John's
5        St. John's
6     Northern Iowa
7     Northern Iowa
8        St. John's
9        St. John's
10    Northern Iowa
11       St. John's
12       St. John's
13       St. John's
14       St. John's
15       St. John's
16       St. John's
17       St. John's
18       St. John's
19       St. John's
20       St. John's
dtype: object


Kansas  ( 79.9% ) vs.  Cal Baptist  ( 20.1% )
1          Kansas
2          Kansas
3          Kansas
4          Kansas
5          Kansas
6          Kansas
7          Kansas
8     Cal Baptist
9          Kansas
10         Kansas
11         Kansas
12    Cal Baptist
13         Kansas
14         Kansas
15         Kansas
16         Kansas
17    Cal Baptist
18    Cal Baptist
19         Kansas
20         Kansas
dtype: object


Louisville  ( 69.5% ) vs.  South Florida  ( 30.5% )
1     South Florida
2     South Florida
3        Louisville
4        Louisville
5        Louisville
6        Louisville
7     South Florida
8        Louisville
9        Louisville
10       Louisville
11       Louisville
12    South Florida
13    South Florida
14       Louisville
15    South Florida
16       Louisville
17       Louisville
18       Louisville
19       Louisville
20       Louisville
dtype: object


Michigan St.  ( 88.5% ) vs.  North Dakota St.  ( 11.5% )
1     North Dakota St.
2         Michigan St.
3         Michigan St.
4         Michigan St.
5         Michigan St.
6         Michigan St.
7         Michigan St.
8         Michigan St.
9         Michigan St.
10        Michigan St.
11        Michigan St.
12        Michigan St.
13        Michigan St.
14        Michigan St.
15        Michigan St.
16        Michigan St.
17        Michigan St.
18        Michigan St.
19    North Dakota St.
20        Michigan St.
dtype: object


UCLA  ( 64.1% ) vs.  UCF  ( 35.9% )
1     UCLA
2     UCLA
3      UCF
4     UCLA
5     UCLA
6     UCLA
7      UCF
8      UCF
9     UCLA
10     UCF
11    UCLA
12    UCLA
13     UCF
14    UCLA
15    UCLA
16    UCLA
17    UCLA
18     UCF
19    UCLA
20     UCF
dtype: object


Uconn  ( 92.1% ) vs.  Furman  ( 7.9% )
1      Uconn
2      Uconn
3      Uconn
4      Uconn
5      Uconn
6      Uconn
7      Uconn
8     Furman
9      Uconn
10     Uconn
11     Uconn
12     Uconn
13    Furman
14     Uconn
15     Uconn
16     Uconn
17     Uconn
18     Uconn
19     Uconn
20     Uconn
dtype: object


Florida  ( 97.7% ) vs.  Prairie View A&M  ( 2.3% )
1              Florida
2              Florida
3              Florida
4              Florida
5              Florida
6              Florida
7              Florida
8              Florida
9              Florida
10             Florida
11    Prairie View A&M
12             Florida
13             Florida
14             Florida
15             Florida
16             Florida
17             Florida
18             Florida
19             Florida
20             Florida
dtype: object


Clemson  ( 43.6% ) vs.  Iowa  ( 56.4% )
1        Iowa
2     Clemson
3        Iowa
4     Clemson
5        Iowa
6        Iowa
7     Clemson
8        Iowa
9     Clemson
10       Iowa
11    Clemson
12    Clemson
13       Iowa
14       Iowa
15       Iowa
16    Clemson
17    Clemson
18    Clemson
19       Iowa
20       Iowa
dtype: object


Vanderbilt  ( 79.0% ) vs.  McNeese  ( 21.0% )
1     Vanderbilt
2     Vanderbilt
3     Vanderbilt
4        McNeese
5     Vanderbilt
6     Vanderbilt
7        McNeese
8     Vanderbilt
9     Vanderbilt
10    Vanderbilt
11    Vanderbilt
12    Vanderbilt
13    Vanderbilt
14    Vanderbilt
15    Vanderbilt
16       McNeese
17       McNeese
18    Vanderbilt
19    Vanderbilt
20    Vanderbilt
dtype: object


Nebraska  ( 85.5% ) vs.  Troy  ( 14.5% )
1     Nebraska
2     Nebraska
3     Nebraska
4     Nebraska
5     Nebraska
6         Troy
7     Nebraska
8     Nebraska
9     Nebraska
10    Nebraska
11    Nebraska
12    Nebraska
13    Nebraska
14    Nebraska
15    Nebraska
16    Nebraska
17    Nebraska
18        Troy
19        Troy
20    Nebraska
dtype: object


North Carolina  ( 62.0% ) vs.  VCU  ( 38.0% )
1                VCU
2     North Carolina
3                VCU
4                VCU
5     North Carolina
6     North Carolina
7     North Carolina
8     North Carolina
9     North Carolina
10               VCU
11    North Carolina
12    North Carolina
13               VCU
14    North Carolina
15               VCU
16    North Carolina
17    North Carolina
18    North Carolina
19    North Carolina
20               VCU
dtype: object


Illinois  ( 92.1% ) vs.  Penn  ( 7.9% )
1     Illinois
2         Penn
3     Illinois
4     Illinois
5     Illinois
6     Illinois
7     Illinois
8     Illinois
9     Illinois
10    Illinois
11        Penn
12    Illinois
13    Illinois
14    Illinois
15    Illinois
16    Illinois
17    Illinois
18    Illinois
19    Illinois
20    Illinois
dtype: object


Saint Mary's  ( 61.0% ) vs.  Texas A&M  ( 39.0% )
1     Saint Mary's
2        Texas A&M
3     Saint Mary's
4        Texas A&M
5     Saint Mary's
6     Saint Mary's
7     Saint Mary's
8        Texas A&M
9        Texas A&M
10    Saint Mary's
11       Texas A&M
12       Texas A&M
13    Saint Mary's
14    Saint Mary's
15       Texas A&M
16    Saint Mary's
17    Saint Mary's
18    Saint Mary's
19    Saint Mary's
20       Texas A&M
dtype: object


Houston  ( 94.7% ) vs.  Idaho  ( 5.3% )
1     Houston
2     Houston
3     Houston
4     Houston
5     Houston
6     Houston
7     Houston
8     Houston
9     Houston
10    Houston
11    Houston
12    Houston
13    Houston
14    Houston
15    Houston
16    Houston
17    Houston
18      Idaho
19    Houston
20    Houston
dtype: object


Arizona  ( 98.2% ) vs.  LIU  ( 1.8% )
1     Arizona
2     Arizona
3     Arizona
4     Arizona
5     Arizona
6     Arizona
7     Arizona
8     Arizona
9     Arizona
10    Arizona
11        LIU
12    Arizona
13    Arizona
14    Arizona
15    Arizona
16    Arizona
17    Arizona
18    Arizona
19    Arizona
20    Arizona
dtype: object


Villanova  ( 48.4% ) vs.  Utah St.  ( 51.6% )
1      Utah St.
2     Villanova
3     Villanova
4      Utah St.
5     Villanova
6     Villanova
7     Villanova
8      Utah St.
9      Utah St.
10    Villanova
11    Villanova
12     Utah St.
13     Utah St.
14    Villanova
15     Utah St.
16     Utah St.
17     Utah St.
18    Villanova
19    Villanova
20     Utah St.
dtype: object


Wisconsin  ( 77.4% ) vs.  High Point  ( 22.6% )
1      Wisconsin
2      Wisconsin
3      Wisconsin
4      Wisconsin
5      Wisconsin
6      Wisconsin
7      Wisconsin
8      Wisconsin
9      Wisconsin
10     Wisconsin
11    High Point
12    High Point
13    High Point
14     Wisconsin
15    High Point
16     Wisconsin
17    High Point
18     Wisconsin
19     Wisconsin
20     Wisconsin
dtype: object


Arkansas  ( 83.7% ) vs.  Hawaii  ( 16.3% )
1     Arkansas
2     Arkansas
3     Arkansas
4     Arkansas
5     Arkansas
6     Arkansas
7     Arkansas
8     Arkansas
9     Arkansas
10      Hawaii
11    Arkansas
12      Hawaii
13    Arkansas
14    Arkansas
15    Arkansas
16    Arkansas
17    Arkansas
18    Arkansas
19    Arkansas
20      Hawaii
dtype: object


BYU  ( 63.3% ) vs.  Texas  ( 36.7% )
1       BYU
2     Texas
3       BYU
4       BYU
5       BYU
6     Texas
7     Texas
8       BYU
9       BYU
10      BYU
11    Texas
12    Texas
13      BYU
14      BYU
15      BYU
16    Texas
17      BYU
18    Texas
19    Texas
20      BYU
dtype: object


Gonzaga  ( 91.4% ) vs.  Kennesaw St.  ( 8.6% )
1          Gonzaga
2     Kennesaw St.
3          Gonzaga
4          Gonzaga
5          Gonzaga
6          Gonzaga
7          Gonzaga
8          Gonzaga
9          Gonzaga
10         Gonzaga
11         Gonzaga
12         Gonzaga
13    Kennesaw St.
14         Gonzaga
15         Gonzaga
16         Gonzaga
17         Gonzaga
18         Gonzaga
19         Gonzaga
20         Gonzaga
dtype: object


Miami (FL)  ( 63.2% ) vs.  Missouri  ( 36.8% )
1     Miami (FL)
2     Miami (FL)
3     Miami (FL)
4       Missouri
5     Miami (FL)
6     Miami (FL)
7       Missouri
8       Missouri
9       Missouri
10      Missouri
11      Missouri
12    Miami (FL)
13    Miami (FL)
14    Miami (FL)
15      Missouri
16    Miami (FL)
17      Missouri
18    Miami (FL)
19    Miami (FL)
20    Miami (FL)
dtype: object


Purdue  ( 93.0% ) vs.  Queens  ( 7.0% )
1     Purdue
2     Purdue
3     Purdue
4     Purdue
5     Purdue
6     Queens
7     Purdue
8     Purdue
9     Purdue
10    Purdue
11    Purdue
12    Purdue
13    Queens
14    Purdue
15    Purdue
16    Purdue
17    Purdue
18    Purdue
19    Purdue
20    Purdue
dtype: object


Michigan  ( 98.0% ) vs.  Howard  ( 2.0% )
1     Michigan
2     Michigan
3     Michigan
4     Michigan
5     Michigan
6       Howard
7     Michigan
8     Michigan
9     Michigan
10    Michigan
11    Michigan
12    Michigan
13    Michigan
14    Michigan
15    Michigan
16    Michigan
17    Michigan
18    Michigan
19    Michigan
20    Michigan
dtype: object


Georgia  ( 51.0% ) vs.  Saint Louis  ( 49.0% )
1         Georgia
2     Saint Louis
3         Georgia
4     Saint Louis
5         Georgia
6         Georgia
7     Saint Louis
8         Georgia
9         Georgia
10    Saint Louis
11    Saint Louis
12        Georgia
13    Saint Louis
14        Georgia
15        Georgia
16    Saint Louis
17    Saint Louis
18    Saint Louis
19        Georgia
20    Saint Louis
dtype: object


Texas Tech  ( 76.2% ) vs.  Akron  ( 23.8% )
1     Texas Tech
2          Akron
3          Akron
4     Texas Tech
5     Texas Tech
6          Akron
7     Texas Tech
8          Akron
9          Akron
10    Texas Tech
11    Texas Tech
12    Texas Tech
13    Texas Tech
14    Texas Tech
15    Texas Tech
16    Texas Tech
17    Texas Tech
18    Texas Tech
19    Texas Tech
20    Texas Tech
dtype: object


Alabama  ( 77.1% ) vs.  Hofstra  ( 22.9% )
1     Alabama
2     Alabama
3     Alabama
4     Alabama
5     Alabama
6     Alabama
7     Alabama
8     Hofstra
9     Alabama
10    Alabama
11    Hofstra
12    Alabama
13    Alabama
14    Alabama
15    Hofstra
16    Alabama
17    Alabama
18    Hofstra
19    Hofstra
20    Alabama
dtype: object


Tennessee  ( 68.2% ) vs.  SMU  ( 31.8% )
1     Tennessee
2     Tennessee
3     Tennessee
4           SMU
5           SMU
6           SMU
7     Tennessee
8     Tennessee
9           SMU
10    Tennessee
11    Tennessee
12    Tennessee
13          SMU
14          SMU
15          SMU
16    Tennessee
17    Tennessee
18    Tennessee
19    Tennessee
20    Tennessee
dtype: object


Virginia  ( 88.8% ) vs.  Wright St.  ( 11.2% )
1       Virginia
2       Virginia
3     Wright St.
4       Virginia
5       Virginia
6       Virginia
7       Virginia
8       Virginia
9       Virginia
10    Wright St.
11      Virginia
12      Virginia
13      Virginia
14      Virginia
15      Virginia
16      Virginia
17      Virginia
18      Virginia
19      Virginia
20      Virginia
dtype: object


Kentucky  ( 59.5% ) vs.  Santa Clara  ( 40.5% )
1        Kentucky
2     Santa Clara
3     Santa Clara
4        Kentucky
5        Kentucky
6        Kentucky
7     Santa Clara
8        Kentucky
9     Santa Clara
10       Kentucky
11    Santa Clara
12    Santa Clara
13       Kentucky
14       Kentucky
15       Kentucky
16       Kentucky
17       Kentucky
18    Santa Clara
19    Santa Clara
20       Kentucky
dtype: object


Iowa St.  ( 94.7% ) vs.  Tennessee St.  ( 5.3% )
1          Iowa St.
2          Iowa St.
3          Iowa St.
4          Iowa St.
5          Iowa St.
6          Iowa St.
7          Iowa St.
8          Iowa St.
9          Iowa St.
10         Iowa St.
11         Iowa St.
12    Tennessee St.
13         Iowa St.
14         Iowa St.
15         Iowa St.
16         Iowa St.
17         Iowa St.
18         Iowa St.
19         Iowa St.
20         Iowa St.
dtype: object

In [15]:
team1 = "Purdue"
team2 = 'Duke'
print (team1, ' vs. ', team2)
print (get_dartboard_numbers(team1, team2, rankings, dartboard_numbers, dartboard_weights))

Purdue  vs.  Duke
1       Duke
2       Duke
3       Duke
4       Duke
5       Duke
6     Purdue
7       Duke
8       Duke
9       Duke
10      Duke
11    Purdue
12      Duke
13      Duke
14    Purdue
15      Duke
16      Duke
17      Duke
18      Duke
19    Purdue
20      Duke
dtype: object

C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]

In [16]:
team1 = 'Wisconsin'
team2 = 'Illinois'

print (get_win_probabilities(team1, team2,rankings))

print (select_winner(team1, team2,rankings))

(np.float64(0.30645161290322576), np.float64(0.6935483870967742))
Illinois

C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]

In [17]:
second_round = []

for i in range(1,len(bracket),2):
    team1 = bracket['Team'][i]
    team2 = bracket['Team'][i+1]
    second_round.append(select_winner(team1, team2, rankings))

print (second_round)
print ()

sweet_16 = []

for i in range(1,len(second_round),2):
    team1 = second_round[i-1]
    team2 = second_round[i]
    sweet_16.append(select_winner(team1, team2, rankings))

print (sweet_16)
print ()

elite_8 = []

for i in range(1,len(sweet_16),2):
    team1 = sweet_16[i-1]
    team2 = sweet_16[i]
    elite_8.append(select_winner(team1, team2, rankings))

print (elite_8)
print ()

final_4 = []

for i in range(1,len(elite_8),2):
    team1 = elite_8[i-1]
    team2 = elite_8[i]
    final_4.append(select_winner(team1, team2, rankings))

print (final_4)
print ()

nat_champ = []

for i in range(1,len(final_4),2):
    team1 = final_4[i-1]
    team2 = final_4[i]
    nat_champ.append(select_winner(team1, team2, rankings))

print (nat_champ)
print ()

team1 = nat_champ[0]
team2 = nat_champ[1]
winner = select_winner(team1, team2, rankings)
print (winner)

['Duke', 'TCU', 'Northern Iowa', 'Kansas', 'Louisville', 'Michigan St.', 'UCLA', 'Uconn', 'Florida', 'Iowa', 'Vanderbilt', 'Nebraska', 'North Carolina', 'Illinois', 'Texas A&M', 'Houston', 'Arizona', 'Utah St.', 'Wisconsin', 'Arkansas', 'BYU', 'Gonzaga', 'Miami (FL)', 'Purdue', 'Michigan', 'Saint Louis', 'Texas Tech', 'Alabama', 'SMU', 'Virginia', 'Kentucky', 'Iowa St.']

['Duke', 'Kansas', 'Michigan St.', 'Uconn', 'Florida', 'Vanderbilt', 'Illinois', 'Houston', 'Arizona', 'Wisconsin', 'Gonzaga', 'Miami (FL)', 'Saint Louis', 'Texas Tech', 'Virginia', 'Kentucky']

['Kansas', 'Uconn', 'Florida', 'Houston', 'Arizona', 'Gonzaga', 'Texas Tech', 'Kentucky']

['Kansas', 'Houston', 'Arizona', 'Texas Tech']

['Houston', 'Arizona']

Houston

C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]

In [18]:
all_winners = []

In [19]:
test.columns = ["Duke",
"Ohio St.",
"St. John's",
"Kansas",
"Louisville",
"Michigan St.",
"UCLA",
"Uconn",
"Florida",
"Clemson",
"Vanderbilt",
"Nebraska",
"North Carolina",
"Illinois",
"Saint Mary's",
"Houston",
"Arizona",
"Villanova",
"Wisconsin",
"Arkansas",
"BYU",
"Gonzaga",
"Miami (FL)",
"Purdue",
"Michigan",
"Georgia",
"Texas Tech",
"Alabama",
"Tennessee",
"Virginia",
"Kentucky",
"Iowa St.",
"East Sweet 16 1",
"East Sweet 16 2",
"East Sweet 16 3",
"East Sweet 16 4",
"West Sweet 16 1",
"West Sweet 16 2",
"West Sweet 16 3",
"West Sweet 16 4",
"South Sweet 16 1",
"South Sweet 16 2",
"South Sweet 16 3",
"South Sweet 16 4",
"Midwest Sweet 16 1",
"Midwest Sweet 16 2",
"Midwest Sweet 16 3",
"Midwest Sweet 16 4",
"East Elite 8 1",
"East Elite 8 2",
"West Elite 8 1",
"West Elite 8 2",
"South Elite 8 1",
"South Elite 8 2",
"Midwest Elite 8 1",
"Midwest Elite 8 2",
"East Champ",
"West Champ",
"South Champ",
"Midwest Champ",
"Nat Champ 1",
"Nat Champ 2",
"Champion"
]

NameError: name 'test' is not defined

In [27]:
test

,Alabama,Maryland,SDSU,Virginia,Creighton,Baylor,Missouri,Arizona,Purdue,Memphis,...,Midwest Elite 8 2,West Elite 8 1,West Elite 8 2,South Champ,East Champ,Midwest Champ,West Champ,Nat Champ 1,Nat Champ 2,Champion
0,Alabama,W. Virginia,SDSU,Virginia,Creighton,Baylor,Missouri,Arizona,Purdue,Memphis,...,Texas,St. Mary's,UCLA,Alabama,Marquette,Houston,UCLA,Alabama,Houston,Houston

In [32]:
j % 1000

NameError: name 'j' is not defined

In [21]:
winners = []

for j in range(0,10000):
    second_round = []

    for i in range(1,len(bracket),2):
        team1 = bracket['Team'][i]
        team2 = bracket['Team'][i+1]
        second_round.append(select_winner(team1, team2, rankings))

    sweet_16 = []

    for i in range(1,len(second_round),2):
        team1 = second_round[i-1]
        team2 = second_round[i]
        sweet_16.append(select_winner(team1, team2, rankings))

    elite_8 = []

    for i in range(1,len(sweet_16),2):
        team1 = sweet_16[i-1]
        team2 = sweet_16[i]
        elite_8.append(select_winner(team1, team2, rankings))

    final_4 = []

    for i in range(1,len(elite_8),2):
        team1 = elite_8[i-1]
        team2 = elite_8[i]
        final_4.append(select_winner(team1, team2, rankings))

    nat_champ = []

    for i in range(1,len(final_4),2):
        team1 = final_4[i-1]
        team2 = final_4[i]
        nat_champ.append(select_winner(team1, team2, rankings))

    team1 = nat_champ[0]
    team2 = nat_champ[1]
    winner = select_winner(team1, team2, rankings)
    winners.append(winner)
    
    temp = pd.DataFrame(second_round + sweet_16 + elite_8 + final_4 + nat_champ + [winner]).T
    if j == 0:
        brackets2 = temp
    else:
        brackets2 = pd.concat([brackets2, temp], ignore_index=True)
        
    if (j % 1000) == 0:
        print (j, datetime.datetime.now())
        
    #brackets2 = brackets2.append(temp)

C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]

0 2026-03-19 14:04:48.676160

C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]

1000 2026-03-19 14:06:08.055912

C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]

2000 2026-03-19 14:11:47.011203

C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]

3000 2026-03-19 14:18:06.512542

C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]

4000 2026-03-19 14:24:47.061235

C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]

5000 2026-03-19 14:26:57.663119

C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]

6000 2026-03-19 14:30:24.299598

C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]

7000 2026-03-19 14:36:54.461438

C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]

8000 2026-03-19 14:39:56.626110

C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]

9000 2026-03-19 14:41:03.037403

C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team2_total = rankings.loc[team2][1] * 4 + rankings.loc[team2][2] + rankings.loc[team2][3] + rankings.loc[team2][4] + rankings.loc[team2][5]
C:\Users\maasr\AppData\Local\Temp\ipykernel_944\1088193208.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  team1_total = rankings.loc[team1][1] * 4 + rankings.loc[team1][2] + rankings.loc[team1][3] + rankings.loc[team1][4] + rankings.loc[team1][5]

In [22]:
brackets2[62].value_counts()

62
Duke              3764
Arizona           2092
Michigan          1866
Florida            862
Houston            385
Iowa St.           275
Purdue             109
Illinois           105
Uconn               95
Michigan St.        83
Gonzaga             81
Virginia            49
Vanderbilt          41
Arkansas            28
St. John's          18
Texas Tech          18
Wisconsin           18
Louisville          17
Nebraska            17
Tennessee           15
Kansas              11
Alabama             11
BYU                  9
Saint Mary's         5
North Carolina       4
Utah St.             4
Kentucky             3
UCLA                 3
South Florida        2
Miami (FL)           2
Ohio St.             2
Iowa                 2
SMU                  1
Clemson              1
Akron                1
Santa Clara          1
Name: count, dtype: int64

In [23]:
brackets2.columns = ["Duke",
"Ohio St.",
"St. John's",
"Kansas",
"Louisville",
"Michigan St.",
"UCLA",
"Uconn",
"Florida",
"Clemson",
"Vanderbilt",
"Nebraska",
"North Carolina",
"Illinois",
"Saint Mary's",
"Houston",
"Arizona",
"Villanova",
"Wisconsin",
"Arkansas",
"BYU",
"Gonzaga",
"Miami (FL)",
"Purdue",
"Michigan",
"Georgia",
"Texas Tech",
"Alabama",
"Tennessee",
"Virginia",
"Kentucky",
"Iowa St.",
"East Sweet 16 1",
"East Sweet 16 2",
"East Sweet 16 3",
"East Sweet 16 4",
"West Sweet 16 1",
"West Sweet 16 2",
"West Sweet 16 3",
"West Sweet 16 4",
"South Sweet 16 1",
"South Sweet 16 2",
"South Sweet 16 3",
"South Sweet 16 4",
"Midwest Sweet 16 1",
"Midwest Sweet 16 2",
"Midwest Sweet 16 3",
"Midwest Sweet 16 4",
"East Elite 8 1",
"East Elite 8 2",
"West Elite 8 1",
"West Elite 8 2",
"South Elite 8 1",
"South Elite 8 2",
"Midwest Elite 8 1",
"Midwest Elite 8 2",
"East Champ",
"West Champ",
"South Champ",
"Midwest Champ",
"Nat Champ 1",
"Nat Champ 2",
"Champion"
]

In [24]:
brackets2.shape

(10000, 63)

In [25]:
brackets2.to_csv('Simulated_Brackets_10K_2026.csv')

In [26]:
for i in brackets2.columns.values:
    print (brackets2[i].value_counts())
    print ()
    print ()

Duke
Duke     9898
Siena     102
Name: count, dtype: int64


Ohio St.
Ohio St.    5893
TCU         4107
Name: count, dtype: int64


St. John's
St. John's       7727
Northern Iowa    2273
Name: count, dtype: int64


Kansas
Kansas         8036
Cal Baptist    1964
Name: count, dtype: int64


Louisville
Louisville       7133
South Florida    2867
Name: count, dtype: int64


Michigan St.
Michigan St.        8773
North Dakota St.    1227
Name: count, dtype: int64


UCLA
UCLA    6483
UCF     3517
Name: count, dtype: int64


Uconn
Uconn     9208
Furman     792
Name: count, dtype: int64


Florida
Florida             9796
Prairie View A&M     204
Name: count, dtype: int64


Clemson
Iowa       5401
Clemson    4599
Name: count, dtype: int64


Vanderbilt
Vanderbilt    7964
McNeese       2036
Name: count, dtype: int64


Nebraska
Nebraska    8680
Troy        1320
Name: count, dtype: int64


North Carolina
North Carolina    6214
VCU               3786
Name: count, dtype: int64


Illinois
Illinois    9211
Penn         789
Name: count, dtype: int64


Saint Mary's
Saint Mary's    6221
Texas A&M       3779
Name: count, dtype: int64


Houston
Houston    9535
Idaho       465
Name: count, dtype: int64


Arizona
Arizona    9790
LIU         210
Name: count, dtype: int64


Villanova
Utah St.     5109
Villanova    4891
Name: count, dtype: int64


Wisconsin
Wisconsin     7803
High Point    2197
Name: count, dtype: int64


Arkansas
Arkansas    8451
Hawaii      1549
Name: count, dtype: int64


BYU
BYU      6323
Texas    3677
Name: count, dtype: int64


Gonzaga
Gonzaga         9108
Kennesaw St.     892
Name: count, dtype: int64


Miami (FL)
Miami (FL)    6323
Missouri      3677
Name: count, dtype: int64


Purdue
Purdue    9271
Queens     729
Name: count, dtype: int64


Michigan
Michigan    9834
Howard       166
Name: count, dtype: int64


Georgia
Georgia        5205
Saint Louis    4795
Name: count, dtype: int64


Texas Tech
Texas Tech    7718
Akron         2282
Name: count, dtype: int64


Alabama
Alabama    7766
Hofstra    2234
Name: count, dtype: int64


Tennessee
Tennessee    6845
SMU          3155
Name: count, dtype: int64


Virginia
Virginia      8921
Wright St.    1079
Name: count, dtype: int64


Kentucky
Kentucky       5947
Santa Clara    4053
Name: count, dtype: int64


Iowa St.
Iowa St.         9521
Tennessee St.     479
Name: count, dtype: int64


East Sweet 16 1
Duke        9286
Ohio St.     443
TCU          246
Siena         25
Name: count, dtype: int64


East Sweet 16 2
St. John's       4614
Kansas           4207
Northern Iowa     740
Cal Baptist       439
Name: count, dtype: int64


East Sweet 16 3
Michigan St.        5572
Louisville          3331
South Florida        858
North Dakota St.     239
Name: count, dtype: int64


East Sweet 16 4
Uconn     6761
UCLA      2229
UCF        854
Furman     156
Name: count, dtype: int64


West Sweet 16 1
Florida             8474
Iowa                 884
Clemson              607
Prairie View A&M      35
Name: count, dtype: int64


West Sweet 16 2
Vanderbilt    4807
Nebraska      4339
McNeese        643
Troy           211
Name: count, dtype: int64


West Sweet 16 3
Illinois          6777
North Carolina    2123
VCU                921
Penn               179
Name: count, dtype: int64


West Sweet 16 4
Houston         7626
Saint Mary's    1559
Texas A&M        725
Idaho             90
Name: count, dtype: int64


South Sweet 16 1
Arizona      8929
Utah St.      538
Villanova     494
LIU            39
Name: count, dtype: int64


South Sweet 16 2
Arkansas      5095
Wisconsin     3935
High Point     589
Hawaii         381
Name: count, dtype: int64


South Sweet 16 3
Gonzaga         6355
BYU             2433
Texas           1061
Kennesaw St.     151
Name: count, dtype: int64


South Sweet 16 4
Purdue        6851
Miami (FL)    2144
Missouri       868
Queens         137
Name: count, dtype: int64


Midwest Sweet 16 1
Michigan       8985
Georgia         535
Saint Louis     447
Howard           33
Name: count, dtype: int64


Midwest Sweet 16 2
Texas Tech    4677
Alabama       3997
Akron          796
Hofstra        530
Name: count, dtype: int64


Midwest Sweet 16 3
Virginia      5619
Tennessee     3221
SMU            960
Wright St.     200
Name: count, dtype: int64


Midwest Sweet 16 4
Iowa St.         7451
Kentucky         1624
Santa Clara       848
Tennessee St.      77
Name: count, dtype: int64


East Elite 8 1
Duke             8506
St. John's        616
Kansas            535
Ohio St.          201
TCU                82
Northern Iowa      38
Cal Baptist        18
Siena               4
Name: count, dtype: int64


East Elite 8 2
Uconn               3671
Michigan St.        3324
Louisville          1676
UCLA                 787
South Florida        272
UCF                  202
North Dakota St.      44
Furman                24
Name: count, dtype: int64


West Elite 8 1
Florida             6733
Vanderbilt          1436
Nebraska            1146
Iowa                 370
Clemson              238
McNeese               61
Troy                  11
Prairie View A&M       5
Name: count, dtype: int64


West Elite 8 2
Houston           5083
Illinois          3295
North Carolina     625
Saint Mary's       590
VCU                194
Texas A&M          181
Penn                18
Idaho               14
Name: count, dtype: int64


South Elite 8 1
Arizona       7836
Arkansas       958
Wisconsin      679
Utah St.       251
Villanova      214
High Point      38
Hawaii          18
LIU              6
Name: count, dtype: int64


South Elite 8 2
Purdue          4096
Gonzaga         3569
BYU             1001
Miami (FL)       757
Texas            326
Missouri         212
Kennesaw St.      22
Queens            17
Name: count, dtype: int64


Midwest Elite 8 1
Michigan       7866
Texas Tech      931
Alabama         698
Georgia         201
Saint Louis     183
Akron            74
Hofstra          42
Howard            5
Name: count, dtype: int64


Midwest Elite 8 2
Iowa St.         5030
Virginia         2564
Tennessee        1237
Kentucky          643
Santa Clara       262
SMU               232
Wright St.         21
Tennessee St.      11
Name: count, dtype: int64


East Champ
Duke                7405
Uconn                833
Michigan St.         758
Louisville           290
St. John's           256
Kansas               222
UCLA                  77
Ohio St.              75
South Florida         27
TCU                   21
UCF                   18
Northern Iowa          8
North Dakota St.       5
Cal Baptist            4
Furman                 1
Name: count, dtype: int64


West Champ
Florida           4480
Houston           2596
Illinois          1379
Vanderbilt         627
Nebraska           413
North Carolina     153
Saint Mary's       138
Iowa                97
Clemson             55
Texas A&M           24
VCU                 23
McNeese             13
Troy                 1
Penn                 1
Name: count, dtype: int64


South Champ
Arizona         6409
Purdue          1241
Gonzaga         1075
Arkansas         447
Wisconsin        279
BYU              205
Miami (FL)       129
Utah St.          74
Villanova         67
Texas             39
Missouri          26
High Point         7
Kennesaw St.       1
Hawaii             1
Name: count, dtype: int64


Midwest Champ
Michigan         6172
Iowa St.         1891
Virginia          668
Texas Tech        390
Alabama           283
Tennessee         282
Kentucky          108
Georgia            57
Saint Louis        56
Santa Clara        41
SMU                27
Akron              12
Hofstra             9
Howard              3
Tennessee St.       1
Name: count, dtype: int64


Nat Champ 1
Duke              5706
Florida           1829
Houston            875
Illinois           349
Uconn              347
Michigan St.       298
Vanderbilt         147
Louisville          97
St. John's          87
Nebraska            83
Kansas              58
UCLA                24
Saint Mary's        22
Ohio St.            19
North Carolina      19
Iowa                11
South Florida        8
Clemson              6
VCU                  4
Cal Baptist          3
McNeese              2
Texas A&M            2
Northern Iowa        2
TCU                  1
UCF                  1
Name: count, dtype: int64


Nat Champ 2
Arizona        4022
Michigan       3663
Iowa St.        773
Purdue          430
Gonzaga         361
Virginia        206
Arkansas        102
Texas Tech       91
Wisconsin        77
Tennessee        72
Alabama          60
BYU              41
Utah St.         17
Kentucky         15
Villanova        13
Miami (FL)       12
Georgia          11
Texas            10
Saint Louis       8
SMU               4
Missouri          4
Santa Clara       4
Akron             3
High Point        1
Name: count, dtype: int64


Champion
Duke              3764
Arizona           2092
Michigan          1866
Florida            862
Houston            385
Iowa St.           275
Purdue             109
Illinois           105
Uconn               95
Michigan St.        83
Gonzaga             81
Virginia            49
Vanderbilt          41
Arkansas            28
St. John's          18
Texas Tech          18
Wisconsin           18
Louisville          17
Nebraska            17
Tennessee           15
Kansas              11
Alabama             11
BYU                  9
Saint Mary's         5
North Carolina       4
Utah St.             4
Kentucky             3
UCLA                 3
South Florida        2
Miami (FL)           2
Ohio St.             2
Iowa                 2
SMU                  1
Clemson              1
Akron                1
Santa Clara          1
Name: count, dtype: int64